lints.workspace = true

[package]
name = "gix-pathspec"
version = "0.21.0"
repository = "https://github.com/GitoxideLabs/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project dealing magical pathspecs"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2024"
rust-version = "1.88"
include = ["/src/**/*", "/LICENSE-*", "/README.md"]

[lib]
doctest = true

[features]
## Enable thread-safety.
parallel = ["gix-attributes/parallel"]

[dependencies]
gix-glob = { version = "^0.28.0", path = "../gix-glob" }
gix-path = { version = "^0.13.0", path = "../gix-path" }
gix-attributes = { version = "^0.36.0", path = "../gix-attributes" }
gix-config-value = { version = "^0.20.0", path = "../gix-config-value" }
gix-error = { version = "^0.4.0", path = "../gix-error", features = ["bstr"] }

bstr = { version = "1.12.0", default-features = false, features = ["std"] }
bitflags = "2"

[dev-dependencies]
insta = "1.46.3"
gix-testtools = { path = "../tests/tools", features = ["sha1"] }
serial_test = "3.4.0"
